import PDFDocument from "pdfkit";
import { AnalysisRecord } from "@/domain/analysis";
import {
  MARGIN,
  PAGE_WIDTH,
  CONTENT_WIDTH,
  COLORS,
  formatDate,
  sectionTitle,
  bulletList,
  paragraph,
  keyValueRow,
  renderImpactBadge,
  addHeadersAndFooters,
} from "./pdfHelpers";

/**
 * Builds a single PDF combining the latest impact analysis for every
 * server that has one — a cover summary table followed by one condensed
 * section per server. Generated on demand; never persisted, since it is
 * a point-in-time snapshot across servers rather than a single analysis.
 */
export async function buildCombinedReportPdf(records: AnalysisRecord[]): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: MARGIN,
      bufferPages: true,
      info: {
        Title: "Combined Server Impact Analysis Report",
        Author: "Server Version & Patch Impact Analysis",
        Subject: "Latest impact analysis across all servers",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    try {
      renderCover(doc, records);

      doc.addPage();
      sectionTitle(doc, 1, "Summary");
      renderSummaryTable(doc, records);

      records.forEach((record, index) => {
        doc.addPage();
        sectionTitle(doc, `2.${index + 1}`, `${record.hostname} — ${record.component}`);
        keyValueRow(doc, "Server ID", record.serverId);
        keyValueRow(doc, "Current Version", record.comparison.currentVersion);
        keyValueRow(doc, "Latest Version", record.comparison.latestVersion);
        keyValueRow(doc, "Source", record.source === "PLAYBOOK" ? "Uploaded Ansible Playbook" : "Official Release Lookup");
        keyValueRow(doc, "Analysis Generated", formatDate(record.createdAt));
        doc.moveDown(0.4);

        renderImpactBadge(doc, record.impactLevel, record.confidence);
        doc.moveDown(0.4);

        paragraph(doc, record.analysis.executiveSummary);

        doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.navy).text("Top Risks");
        doc.moveDown(0.2);
        bulletList(doc, record.analysis.risks, "No elevated risk factors identified");

        doc.font("Helvetica-Bold").fontSize(10).fillColor(COLORS.navy).text("Recommended Actions");
        doc.moveDown(0.2);
        bulletList(doc, record.analysis.recommendedActions);
      });

      addHeadersAndFooters(
        doc,
        "Combined Server Impact Analysis Report",
        "Combined Report — Analysis Only — No Automated Remediation"
      );
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

function renderSummaryTable(doc: PDFKit.PDFDocument, records: AnalysisRecord[]) {
  if (records.length === 0) {
    paragraph(doc, "No servers have a completed impact analysis yet.");
    return;
  }

  doc.table({
    columnStyles: ["*", "*", 70, 70, 60],
    defaultStyle: { padding: 6, border: 1, borderColor: COLORS.border, textColor: COLORS.slate },
    data: [
      [
        { text: "Server", font: { family: "Helvetica-Bold" }, backgroundColor: COLORS.panel },
        { text: "Component", font: { family: "Helvetica-Bold" }, backgroundColor: COLORS.panel },
        { text: "Current", font: { family: "Helvetica-Bold" }, backgroundColor: COLORS.panel },
        { text: "Latest", font: { family: "Helvetica-Bold" }, backgroundColor: COLORS.panel },
        { text: "Impact", font: { family: "Helvetica-Bold" }, backgroundColor: COLORS.panel },
      ],
      ...records.map((record) => [
        record.hostname,
        record.component,
        record.comparison.currentVersion,
        record.comparison.latestVersion,
        record.impactLevel,
      ]),
    ],
  });
  doc.moveDown(0.6);
}

function renderCover(doc: PDFKit.PDFDocument, records: AnalysisRecord[]) {
  doc.rect(0, 0, PAGE_WIDTH, 210).fill(COLORS.navy);

  doc
    .fillColor(COLORS.white)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text("SERVER VERSION & PATCH IMPACT ANALYSIS", MARGIN, 60, { characterSpacing: 1 });

  doc
    .fillColor(COLORS.white)
    .font("Helvetica-Bold")
    .fontSize(28)
    .text("Combined Impact Analysis Report", MARGIN, 90, { width: CONTENT_WIDTH });

  doc
    .fillColor("#cbd5e1")
    .font("Helvetica")
    .fontSize(12)
    .text(`${records.length} server(s) — latest analysis per server`, MARGIN, 150);

  doc.y = 260;
  doc.fillColor(COLORS.slate);
  keyValueRow(doc, "Generated", formatDate(new Date().toISOString()));
  keyValueRow(doc, "Servers Included", String(records.length));

  doc.moveDown(2);
  doc
    .fillColor(COLORS.muted)
    .fontSize(9)
    .text(
      "This report is a technical assessment generated by the Server Version & Patch Impact Analysis platform. It is analysis-only and contains no automated remediation actions.",
      MARGIN,
      doc.y,
      { width: CONTENT_WIDTH }
    );
}
